/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package component;

import model.TimeHandler;
import model.User.User;
import myinterface.Observer;
import myinterface.Subject;

/**
 *
 * @author Yun_c
 */
public class BasicInfoPanel extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form BasicInfoPanel
     */
    public BasicInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dayPre = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        money = new javax.swing.JLabel();
        moneyPre = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bagButton = new component.Button();
        jSeparator3 = new javax.swing.JSeparator();
        energyBar = new javax.swing.JProgressBar();
        energyPre = new javax.swing.JLabel();
        energy = new javax.swing.JLabel();
        slice = new javax.swing.JLabel();
        maxEnergy = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        dayPre.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        dayPre.setText("DAY");

        day.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        day.setText("1");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        money.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        money.setText("0");

        moneyPre.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        moneyPre.setText("Money");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        bagButton.setText("BAG");
        
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        energyBar.setForeground(new java.awt.Color(255, 153, 51));

        energyPre.setText("Energy");

        energy.setText("0");

        slice.setText("/");

        maxEnergy.setText("100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayPre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moneyPre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(money)
                .addGap(61, 61, 61)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bagButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(energyPre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(energyBar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(energy, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(slice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maxEnergy)
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dayPre)
                                .addComponent(day))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(money)
                                .addComponent(moneyPre))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(bagButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(energy, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(slice)
                        .addComponent(maxEnergy))
                    .addComponent(energyPre)
                    .addComponent(energyBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.Button bagButton;
    private javax.swing.JLabel day;
    private javax.swing.JLabel dayPre;
    private javax.swing.JLabel energy;
    private javax.swing.JProgressBar energyBar;
    private javax.swing.JLabel energyPre;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel maxEnergy;
    private javax.swing.JLabel money;
    private javax.swing.JLabel moneyPre;
    private javax.swing.JLabel slice;
    // End of variables declaration//GEN-END:variables
    public Button getBag() {
        return this.bagButton;
    }

    @Override
    public void update(Subject s) {
        User u = null;
        if (s instanceof User) {
            u = (User) s;
            int eng = u.getEnergy();
            int engMax = u.getMax_energy();
            int mn = u.getMoney();
            this.energyBar.setMaximum(engMax);
            this.energyBar.setValue(eng);
            this.money.setText(mn + "");
            this.energy.setText(eng + "");
            this.maxEnergy.setText(engMax + "");
        }else if (s instanceof TimeHandler){
            this.day.setText(TimeHandler.getInstance().getDays()+"");
        }

    }

}
