/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package component;

import controller.MapDragController;
import java.util.Random;
import model.BusinessPoint.BusinessPoint;
import model.Path.Path;
import model.WorldMap.WorldMap;

/**
 *
 * @author Yun_c
 */
public class WorldMapPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorldMap
     */
    public WorldMapPanel() {
        initComponents();
        this.jScrollPane1.addMouseMotionListener(new MapDragController());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jScrollPane1.setBorder(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(null);
        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private BusinessPointOnMap[] businessPoints;

    public void initWorldMap(BusinessPoint[] bps, Path[] paths) {
        businessPoints = new BusinessPointOnMap[bps.length];
        WorldMap wMap = WorldMap.getInstance();
        int bpWidth = 50;
        int bpHeight = 50;
        int maxX = this.getParent().getWidth() - bpWidth;
        int maxY = this.getParent().getHeight() - bpHeight;
        Random rnd = new Random();
        for (int i = 0; i < bps.length; i++) {
            this.businessPoints[i] = new BusinessPointOnMap(bps[i]);
            if (i == 0) {
                this.businessPoints[i].setBounds(maxX / 2, maxY / 2, bpWidth, bpHeight);
            } else {
                boolean seperate = false;
                int bp_x = 0;
                int bp_y = 0;
                while (!seperate) {
                    boolean jump = false;
                    bp_x = rnd.nextInt(maxX);
                    bp_y = rnd.nextInt(maxY);
                    for (int j = 0; j < i; j++) {
                        if (bp_x > this.businessPoints[j].getX() + bpWidth + 50
                                || bp_x + bpWidth < this.businessPoints[j].getX() - 50
                                || bp_y > this.businessPoints[j].getY() + bpHeight + 50
                                || bp_y + bpHeight < this.businessPoints[j].getY() - 50) {
                        } else {
                            jump = true;
                            break;
                        }
                    }
                    if (!jump) {
                        seperate = true;
                    }
                }
                this.businessPoints[i].setBounds(bp_x, bp_y, bpWidth, bpHeight);
            }
            this.jPanel1.add(this.businessPoints[i]);
            wMap.attach(this.businessPoints[i]);
        }

    }

}
